<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankIntegrationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bankIntegrations = [
            [
                'id' => 1,
                'name' => 'Türkiye İş Bankası',
                'bank_code' => 'isbank',
                'json' => '{"workplace_code":"","store_key":"","url":"https://sanalpos.isbank.com.tr/servlet/est3Dgate"}',
                'automatic_single_payment' => 1,
                'message' => null,
                'erp_bank_code' => '108 04',
                'company_id' => 1,
                'color' => '#004B8D',
                'logo_path' => 'isbank.svg',
                'is_active' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Garanti BBVA',
                'bank_code' => 'garanti',
                'json' => '{"strStoreKey":"","strProvisionPassword":"","strTerminalMerchantID":"","strTerminalID_":"","strTerminalID":""}',
                'automatic_single_payment' => 0,
                'message' => null,
                'erp_bank_code' => '108 07',
                'company_id' => 1,
                'color' => '#00A651',
                'logo_path' => 'garanti.svg',
                'is_active' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'VakıfBank',
                'bank_code' => 'vakifbank',
                'json' => '{"IsyeriNo":"","TerminalNo":"","IsyeriSifre":""}',
                'automatic_single_payment' => 0,
                'message' => null,
                'erp_bank_code' => '108 01',
                'company_id' => 1,
                'color' => '#FFB81C',
                'logo_path' => 'vakifbank.svg',
                'is_active' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Ziraat Bankası',
                'bank_code' => 'ziraat',
                'json' => '{"workplace_code":"","store_key":"","url":"https://sanalpos2.ziraatbank.com.tr/fim/est3Dgate"}',
                'automatic_single_payment' => 0,
                'message' => null,
                'erp_bank_code' => '108 03',
                'company_id' => 1,
                'color' => '#E30613',
                'logo_path' => 'ziraatbankasi.svg',
                'is_active' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Vakıf Katılım Bankası',
                'bank_code' => 'vakif_katilim',
                'json' => '{"MerchantId":"","CustomerId":"","UserName":"api","Password":""}',
                'automatic_single_payment' => 0,
                'message' => null,
                'erp_bank_code' => '108 11',
                'company_id' => 1,
                'color' => '#7F3F98',
                'logo_path' => 'vakifkatilim.svg',
                'is_active' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'QNB Finansbank',
                'bank_code' => 'qnb',
                'json' => '{"MerchantID":"","UserCode":"api","UserPass":"","StoreKey":""}',
                'automatic_single_payment' => 0,
                'message' => null,
                'erp_bank_code' => '108 02',
                'company_id' => 1,
                'color' => '#4F2683',
                'logo_path' => 'qnb.svg',
                'is_active' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'Akbank',
                'bank_code' => 'akbank',
                'json' => '{"merchantSafeId":"","terminalSafeId":"","subMerchantId":"","secretKey":""}',
                'automatic_single_payment' => 0,
                'message' => null,
                'erp_bank_code' => '108 06',
                'company_id' => 1,
                'color' => '#E60000',
                'logo_path' => 'akbank.svg',
                'is_active' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'DenizBank',
                'bank_code' => 'denizbank',
                'json' => '{"ShopCode":"","StoreKey":""}',
                'automatic_single_payment' => 0,
                'message' => null,
                'erp_bank_code' => '108 05',
                'company_id' => 1,
                'color' => '#004B8D',
                'logo_path' => 'denizbank.svg',
                'is_active' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'Yapı Kredi',
                'bank_code' => 'yapikredi',
                'json' => '{"merchantId":"","terminalId":"","posnetId":"","encKey":""}',
                'automatic_single_payment' => 0,
                'message' => null,
                'erp_bank_code' => '108 10',
                'company_id' => 1,
                'color' => '#1E4B85',
                'logo_path' => 'yapikredi.svg',
                'is_active' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'Halkbank',
                'bank_code' => 'halkbank',
                'json' => '{"workplace_code":"","store_key":"","url":"https://sanalpos.halkbank.com.tr/fim/est3Dgate"}',
                'automatic_single_payment' => 0,
                'message' => null,
                'erp_bank_code' => '108 08',
                'company_id' => 1,
                'color' => '#005CA9',
                'logo_path' => 'halkbank.svg',
                'is_active' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'TEB',
                'bank_code' => 'teb',
                'json' => '{"workplace_code":"","store_key":"","url":"https://sanalpos.teb.com.tr/fim/est3Dgate"}',
                'automatic_single_payment' => 0,
                'message' => null,
                'erp_bank_code' => '108 09',
                'company_id' => 1,
                'color' => '#009639',
                'logo_path' => 'teb.svg',
                'is_active' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ];

        DB::table('bank_integrations')->upsert(
            $bankIntegrations,
            [
                'id',
            ],
            [
                'name',
                'bank_code',
                'json',
                'automatic_single_payment',
                'message',
                'erp_bank_code',
                'company_id',
                'color',
                'logo_path',
                'is_active',
                'status',
                'updated_at',
                'deleted_at',
            ]
        );
    }
}
