<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            [
                'id' => 1,
                'name' => 'ADANA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => '2022-04-11 04:33:26',
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'ADIYAMAN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'AFYON',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'AĞRI',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'AMASYA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'ANKARA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'ANTALYA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'ARTVİN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'AYDIN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'BALIKESİR',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'BİLECİK',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'BİNGÖL',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'BİTLİS',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'BOLU',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'BURDUR',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'BURSA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'ÇANAKKALE',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'name' => 'ÇANKIRI',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'name' => 'ÇORUM',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'name' => 'DENİZLİ',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'name' => 'DİYARBAKIR',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'name' => 'EDİRNE',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'name' => 'ELAZIĞ',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'name' => 'ERZİNCAN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'name' => 'ERZURUM',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'name' => 'ESKİŞEHİR',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'name' => 'GAZİANTEP',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'name' => 'GİRESUN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'name' => 'GÜMÜŞHANE',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'name' => 'HAKKARİ',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'name' => 'HATAY',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'name' => 'ISPARTA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'name' => 'MERSİN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 34,
                'name' => 'İSTANBUL',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 35,
                'name' => 'İZMİR',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 36,
                'name' => 'KARS',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'name' => 'KASTAMONU',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'name' => 'KAYSERİ',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'name' => 'KIRKLARELİ',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'name' => 'KIRŞEHİR',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 41,
                'name' => 'KOCAELİ',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 42,
                'name' => 'KONYA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 43,
                'name' => 'KÜTAHYA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 44,
                'name' => 'MALATYA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 45,
                'name' => 'MANİSA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 46,
                'name' => 'KAHRAMANMARAŞ',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 47,
                'name' => 'MARDİN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'name' => 'MUĞLA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 49,
                'name' => 'MUŞ',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 50,
                'name' => 'NEVŞEHİR',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 51,
                'name' => 'NİĞDE',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 52,
                'name' => 'ORDU',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 53,
                'name' => 'RİZE',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 54,
                'name' => 'SAKARYA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 55,
                'name' => 'SAMSUN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 56,
                'name' => 'SİİRT',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 57,
                'name' => 'SİNOP',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 58,
                'name' => 'SİVAS',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 59,
                'name' => 'TEKİRDAĞ',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 60,
                'name' => 'TOKAT',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 61,
                'name' => 'TRABZON',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 62,
                'name' => 'TUNCELİ',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 63,
                'name' => 'ŞANLIURFA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 64,
                'name' => 'UŞAK',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 65,
                'name' => 'VAN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 66,
                'name' => 'YOZGAT',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 67,
                'name' => 'ZONGULDAK',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 68,
                'name' => 'AKSARAY',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 69,
                'name' => 'BAYBURT',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 70,
                'name' => 'KARAMAN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 71,
                'name' => 'KIRIKKALE',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 72,
                'name' => 'BATMAN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 73,
                'name' => 'ŞIRNAK',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 74,
                'name' => 'BARTIN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 75,
                'name' => 'ARDAHAN',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 76,
                'name' => 'IĞDIR',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 77,
                'name' => 'YALOVA',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 78,
                'name' => 'KARABÜK',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 79,
                'name' => 'KİLİS',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 80,
                'name' => 'OSMANİYE',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 81,
                'name' => 'DÜZCE',
                'country_id' => 1,
                'status' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ];

        DB::table('cities')->upsert(
            $cities,
            ['id'],
            array_diff(array_keys($cities[0]), ['id', 'created_at'])
        );
    }
}