<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InstallmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $installments = [
            [
                'id' => 1,
                'bank_integration_id' => 1,
                'installment' => 1,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'bank_integration_id' => 1,
                'installment' => 2,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'bank_integration_id' => 1,
                'installment' => 3,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'bank_integration_id' => 1,
                'installment' => 4,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'bank_integration_id' => 1,
                'installment' => 5,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'bank_integration_id' => 1,
                'installment' => 6,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'bank_integration_id' => 1,
                'installment' => 7,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'bank_integration_id' => 1,
                'installment' => 8,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'bank_integration_id' => 1,
                'installment' => 9,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'bank_integration_id' => 1,
                'installment' => 10,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'bank_integration_id' => 1,
                'installment' => 11,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'bank_integration_id' => 1,
                'installment' => 12,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'bank_integration_id' => 2,
                'installment' => 1,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'bank_integration_id' => 2,
                'installment' => 2,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'bank_integration_id' => 2,
                'installment' => 3,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'bank_integration_id' => 2,
                'installment' => 4,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'bank_integration_id' => 2,
                'installment' => 5,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'bank_integration_id' => 2,
                'installment' => 6,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'bank_integration_id' => 2,
                'installment' => 7,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'bank_integration_id' => 2,
                'installment' => 8,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'bank_integration_id' => 2,
                'installment' => 9,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'bank_integration_id' => 2,
                'installment' => 10,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'bank_integration_id' => 2,
                'installment' => 11,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'bank_integration_id' => 2,
                'installment' => 12,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'bank_integration_id' => 3,
                'installment' => 1,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'bank_integration_id' => 3,
                'installment' => 2,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'bank_integration_id' => 3,
                'installment' => 3,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'bank_integration_id' => 3,
                'installment' => 4,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'bank_integration_id' => 3,
                'installment' => 5,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'bank_integration_id' => 3,
                'installment' => 6,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'bank_integration_id' => 3,
                'installment' => 7,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'bank_integration_id' => 3,
                'installment' => 8,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'bank_integration_id' => 3,
                'installment' => 9,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'bank_integration_id' => 3,
                'installment' => 10,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'bank_integration_id' => 3,
                'installment' => 11,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'bank_integration_id' => 3,
                'installment' => 12,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'bank_integration_id' => 4,
                'installment' => 1,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'bank_integration_id' => 4,
                'installment' => 2,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'bank_integration_id' => 4,
                'installment' => 3,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'bank_integration_id' => 4,
                'installment' => 4,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'bank_integration_id' => 4,
                'installment' => 5,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'bank_integration_id' => 4,
                'installment' => 6,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'bank_integration_id' => 4,
                'installment' => 7,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'bank_integration_id' => 4,
                'installment' => 8,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'bank_integration_id' => 4,
                'installment' => 9,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'bank_integration_id' => 4,
                'installment' => 10,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'bank_integration_id' => 4,
                'installment' => 11,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'bank_integration_id' => 4,
                'installment' => 12,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'bank_integration_id' => 5,
                'installment' => 1,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'bank_integration_id' => 5,
                'installment' => 2,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'bank_integration_id' => 5,
                'installment' => 3,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'bank_integration_id' => 5,
                'installment' => 4,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'bank_integration_id' => 5,
                'installment' => 5,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'bank_integration_id' => 5,
                'installment' => 6,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'bank_integration_id' => 5,
                'installment' => 7,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'bank_integration_id' => 5,
                'installment' => 8,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'bank_integration_id' => 5,
                'installment' => 9,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'bank_integration_id' => 5,
                'installment' => 10,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'bank_integration_id' => 5,
                'installment' => 11,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'bank_integration_id' => 5,
                'installment' => 12,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'bank_integration_id' => 6,
                'installment' => 1,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'bank_integration_id' => 6,
                'installment' => 2,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'bank_integration_id' => 6,
                'installment' => 3,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'bank_integration_id' => 6,
                'installment' => 4,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'bank_integration_id' => 6,
                'installment' => 5,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'bank_integration_id' => 6,
                'installment' => 6,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'bank_integration_id' => 6,
                'installment' => 7,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'bank_integration_id' => 6,
                'installment' => 8,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'bank_integration_id' => 6,
                'installment' => 9,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 83,
                'bank_integration_id' => 6,
                'installment' => 10,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'bank_integration_id' => 6,
                'installment' => 11,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'bank_integration_id' => 6,
                'installment' => 12,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'bank_integration_id' => 7,
                'installment' => 1,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'bank_integration_id' => 7,
                'installment' => 2,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'bank_integration_id' => 7,
                'installment' => 3,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'bank_integration_id' => 7,
                'installment' => 4,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'bank_integration_id' => 7,
                'installment' => 5,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'bank_integration_id' => 7,
                'installment' => 6,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'bank_integration_id' => 7,
                'installment' => 7,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'bank_integration_id' => 7,
                'installment' => 8,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'bank_integration_id' => 7,
                'installment' => 9,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'bank_integration_id' => 7,
                'installment' => 10,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'bank_integration_id' => 7,
                'installment' => 11,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'bank_integration_id' => 7,
                'installment' => 12,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'bank_integration_id' => 8,
                'installment' => 1,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'bank_integration_id' => 8,
                'installment' => 2,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'bank_integration_id' => 8,
                'installment' => 3,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'bank_integration_id' => 8,
                'installment' => 4,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'bank_integration_id' => 8,
                'installment' => 5,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'bank_integration_id' => 8,
                'installment' => 6,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'bank_integration_id' => 8,
                'installment' => 7,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'bank_integration_id' => 8,
                'installment' => 8,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'bank_integration_id' => 8,
                'installment' => 9,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'bank_integration_id' => 8,
                'installment' => 10,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'bank_integration_id' => 8,
                'installment' => 11,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'bank_integration_id' => 8,
                'installment' => 12,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 110,
                'bank_integration_id' => 9,
                'installment' => 1,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 111,
                'bank_integration_id' => 9,
                'installment' => 2,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 112,
                'bank_integration_id' => 9,
                'installment' => 3,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 113,
                'bank_integration_id' => 9,
                'installment' => 4,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 114,
                'bank_integration_id' => 9,
                'installment' => 5,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 115,
                'bank_integration_id' => 9,
                'installment' => 6,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 116,
                'bank_integration_id' => 9,
                'installment' => 7,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 117,
                'bank_integration_id' => 9,
                'installment' => 8,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 118,
                'bank_integration_id' => 9,
                'installment' => 9,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 119,
                'bank_integration_id' => 9,
                'installment' => 10,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 120,
                'bank_integration_id' => 9,
                'installment' => 11,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 121,
                'bank_integration_id' => 9,
                'installment' => 12,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 98,
                'bank_integration_id' => 10,
                'installment' => 1,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'bank_integration_id' => 10,
                'installment' => 2,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 100,
                'bank_integration_id' => 10,
                'installment' => 3,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'bank_integration_id' => 10,
                'installment' => 4,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 102,
                'bank_integration_id' => 10,
                'installment' => 5,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'bank_integration_id' => 10,
                'installment' => 6,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 104,
                'bank_integration_id' => 10,
                'installment' => 7,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 105,
                'bank_integration_id' => 10,
                'installment' => 8,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 106,
                'bank_integration_id' => 10,
                'installment' => 9,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 107,
                'bank_integration_id' => 10,
                'installment' => 10,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 108,
                'bank_integration_id' => 10,
                'installment' => 11,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 109,
                'bank_integration_id' => 10,
                'installment' => 12,
                'plus_installment' => 0,
                'commission_rate' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('installments')->upsert(
            $installments,
            [
                'id',
            ],
            [
                'bank_integration_id',
                'installment',
                'plus_installment',
                'commission_rate',
                'status',
                'updated_at',
            ]
        );
    }
}
