<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'id' => 1,
                'current_account_id' => 1,
                'name' => 'TEST SALESMAN',
                'code' => 1,
                'group_code' => null,
                'province' => null,
                'district' => null,
                'address' => null,
                'address_1' => null,
                'address_2' => null,
                'address_3' => null,
                'postal_code' => null,
                'tax_office' => null,
                'tax_number' => null,
                'identity_number' => null,
                'email' => 'testsalesman@siteadi.com',
                'email_verified_at' => null,
                'phone' => 5000000000,
                'dealer_code' => null,
                'username' => '01',
                'password' => Hash::make(env('DEFAULT_USER_PASSWORD', 'change-me')),
                'remember_token' => null,
                'balance' => 0,
                'currency_balance' => 0,
                'currency' => 'TL',
                'status' => 1,
                'block_entry' => 0,
                'last_login_date' => null,
                'last_login_ip' => null,
                'admin_last_login_date' => null,
                'hide_category_ids' => null,
                'hidden_product_prefixes' => null,
                'hide_all_prices' => 0,
                'show_retail_price' => 0,
                'hide_all_stock_quantities' => 1,
                'group_by_product_code' => 0,
                'report_access' => 1,
                'min_stock_quantity' => 1,
                'plasiyer1' => null,
                'plasiyer2' => null,
                'plasiyer3' => null,
                'plasiyer4' => null,
                'plasiyer5' => null,
                'plasiyer1_discount1' => 0,
                'plasiyer1_discount2' => 0,
                'plasiyer2_discount1' => 0,
                'plasiyer2_discount2' => 0,
                'payment_reference' => null,
                'payment_type' => null,
                'increase_and_decrease_type' => 1,
                'increase_and_decrease_rate' => 0,
                'price_type' => 1,
                'is_order_closed' => 0,
                'closure_reason' => null,
                'password_must_change' => 1,
                'password_reset_code' => null,
                'password_reset_expires_at' => null,
                'access_type' => 'all_customers',
                'receipt_enabled' => 1,
                'show_all_installments' => 1,
                'can_edit_price' => 1,
                'can_edit_discount' => 1,
                'company_id' => 1,
                'can_collect_payments' => 1,
                'role' => 'salesman',
                'is_installment_allowed' => 1,
                'max_installment' => 12,
                'allowed_payment_methods' => 'cash,credit,term',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'current_account_id' => 500,
                'name' => 'TEST DEALER',
                'code' => 123456789,
                'group_code' => 123456789,
                'province' => 'KADIKÖY',
                'district' => 'İSTANBUL',
                'address' => null,
                'address_1' => 'Fenerbahçe Mah. xx Sokak No:xx Daire: xx Kadiköy İstanbul',
                'address_2' => null,
                'address_3' => null,
                'postal_code' => 34265,
                'tax_office' => 'KADIKÖY VD',
                'tax_number' => 1234567890,
                'identity_number' => null,
                'email' => 'testdealer@siteadi.com',
                'email_verified_at' => null,
                'phone' => 5000000000,
                'dealer_code' => 123456789,
                'username' => 'testdealer',
                'password' => Hash::make(env('DEFAULT_USER_PASSWORD', 'change-me')),
                'remember_token' => null,
                'balance' => 0,
                'currency_balance' => 0,
                'currency' => 'TL',
                'status' => 1,
                'block_entry' => 0,
                'last_login_date' => null,
                'last_login_ip' => null,
                'admin_last_login_date' => null,
                'hide_category_ids' => null,
                'hidden_product_prefixes' => null,
                'hide_all_prices' => 0,
                'show_retail_price' => 0,
                'hide_all_stock_quantities' => 0,
                'group_by_product_code' => 0,
                'report_access' => 1,
                'min_stock_quantity' => 1,
                'plasiyer1' => 1,
                'plasiyer2' => null,
                'plasiyer3' => null,
                'plasiyer4' => null,
                'plasiyer5' => null,
                'plasiyer1_discount1' => 0,
                'plasiyer1_discount2' => 0,
                'plasiyer2_discount1' => 0,
                'plasiyer2_discount2' => 0,
                'payment_reference' => null,
                'payment_type' => null,
                'increase_and_decrease_type' => 1,
                'increase_and_decrease_rate' => 0,
                'price_type' => 1,
                'is_order_closed' => 0,
                'closure_reason' => null,
                'password_must_change' => 0,
                'password_reset_code' => null,
                'password_reset_expires_at' => null,
                'access_type' => null,
                'receipt_enabled' => 1,
                'show_all_installments' => 1,
                'can_edit_price' => 0,
                'can_edit_discount' => 1,
                'company_id' => 1,
                'can_collect_payments' => 1,
                'role' => 'dealer',
                'is_installment_allowed' => 1,
                'max_installment' => 12,
                'allowed_payment_methods' => 'cash,credit,term',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ];

        DB::table('users')->upsert(
            $users,
            [
                'id',
            ],
            [
                'current_account_id',
                'name',
                'code',
                'group_code',
                'province',
                'district',
                'address',
                'address_1',
                'address_2',
                'address_3',
                'postal_code',
                'tax_office',
                'tax_number',
                'identity_number',
                'email',
                'email_verified_at',
                'phone',
                'dealer_code',
                'username',
                'password',
                'remember_token',
                'balance',
                'currency_balance',
                'currency',
                'status',
                'block_entry',
                'last_login_date',
                'last_login_ip',
                'admin_last_login_date',
                'hide_category_ids',
                'hidden_product_prefixes',
                'hide_all_prices',
                'show_retail_price',
                'hide_all_stock_quantities',
                'group_by_product_code',
                'report_access',
                'min_stock_quantity',
                'plasiyer1',
                'plasiyer2',
                'plasiyer3',
                'plasiyer4',
                'plasiyer5',
                'plasiyer1_discount1',
                'plasiyer1_discount2',
                'plasiyer2_discount1',
                'plasiyer2_discount2',
                'payment_reference',
                'payment_type',
                'increase_and_decrease_type',
                'increase_and_decrease_rate',
                'price_type',
                'is_order_closed',
                'closure_reason',
                'password_must_change',
                'password_reset_code',
                'password_reset_expires_at',
                'access_type',
                'receipt_enabled',
                'show_all_installments',
                'can_edit_price',
                'can_edit_discount',
                'company_id',
                'can_collect_payments',
                'role',
                'is_installment_allowed',
                'max_installment',
                'allowed_payment_methods',
                'updated_at',
                'deleted_at',
            ]
        );
    }
}
